### ISSUE TITLE
General Working

### ISSUE THREAD

**Issue by varunsmhatre** [Rakshith2597/Lung-nodule-detection-LUNA-16#1]
Hello there. Thanks for this great work. I just finished a course on Convolutional Neural Networks and want to do a good project to get a better understanding of CNN. So as a beginner, I have no idea about the project. So could you tell me the order in which I should run the files and the basic task the python file does? Thanks in Advance.

**Comment by Rakshith2597** [comment]
This work was done a year ago, I don't clearly remember what exactly each one does. You can get started by executing in the following order.
1. Download the dataset
2. Execute the jupyter notebook- luna_mask.ipynb in data_prep folder
3. Run the train script in train_codes folder.
4. Execute luna_inference.py in Plots folder.

**Comment by varunsmhatre** [comment]
Thanks for the help!!!
