### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by MjdMahasneh** [Rakshith2597/Lung-nodule-detection-LUNA-16#2]
Hello,

I am very interested in reproducing your work, I am  currently working on LUNA-16 nodule detection. I would really appreciate and it would be very helpful if you point out or provide the documentation of your work. This could be wither your paper or thesis (if exists). This would help me and others to further understand the workflow and will assist in reproducing your work.

Looking forward to hearing back from you.

Many thanks.

**Comment by Rakshith2597** [comment]
Hello, This work was done during my under graduation and I do not have the digital/soft copy of the report as of now. You can refer to a more recent work of mine on the same topic here [paper](https://arxiv.org/abs/2006.09308 ). The codes for work explained in this paper has not been uploaded in Github yet, but would help you in understanding the task.
