### ISSUE TITLE
What does 'Masks' refer to?

### ISSUE THREAD

**Issue by MjdMahasneh** [Rakshith2597/Lung-nodule-detection-LUNA-16#3]
Hello,

My question here might have a few parts that are somehow correlated, it might not make sense to reader but I will try to make it as clear as possible. 

1-I have noticed you're using the term detection. This commonly (but not exclusively) refers to detection in the form of bounding boxes. However, your implementation (and Abstract) seems to be referring to only solving the classification problem. **Is my understanding correct?**

2-You also refer to using 'Masks', as I managed to interpret some of the script, I think you are creating masks of rectangular shape using the LUNA-16 ground-truth. where 0s correspond to background and 1s denote nodules. Then you're training a UNet-like network to perform segmentation (initially) and then interpreting the resulting masks as final classification (or detection in the form of bounding boxes?). So to clarify my questions : 
**a- If you're using masks as described above, What is the intuition behind these masks (i.e. how are they being created)?**
**b- what is the final output of the framework, is it in the form of bounding boxes, or is it only the classification per input.**

Looking forward for your response.

Many thanks.

**Comment by Rakshith2597** [comment]
**2. a**) Here, '**masks**' refers to the Ground truth/segmentation map generated from the annotation given for each nodule in the LUNA16 dataset. For each nodule, its (x,y,z) coordinates and its diameter is provided in the dataset which was used to generate these 'masks'. You can find the script [here](https://github.com/Rakshith2597/Lung-nodule-detection-LUNA-16/blob/master/data_prep/luna_mask.ipynb). 
**2 b)** Output is not in the form of bounding boxes. Here we segment the lung nodules and identify(detect) the malignant nodules from it, i.e; classify them based on their diameter. Here I used the word detection as a synonym for identification, I did not mean 
to term it as a 'detection model'.
**1)** Yes, I believe the explanation given above explains this question as well.
